version: '3.9'
services:
  angular:
    hostname: localhost
    container_name: angular
    image: angular
    restart: unless-stopped
    build: .
    ports:
      - 80:80
  server:
    hostname: localhost
    container_name: server
    image: server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./server/Dockerfile  
    ports: 
      - 49160:8080